name: flutter_bluetooth_serial
version: 0.4.0
description: Flutter basic implementation for Classical Bluetooth (only RFCOMM for now).
homepage: https://github.com/edufolly/flutter_bluetooth_serial
repository: https://github.com/edufolly/flutter_bluetooth_serial
issue_tracker: https://github.com/edufolly/flutter_bluetooth_serial/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  io: ^1.0.4
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^3.0.1
  flutter_lints: ">=2.0.2 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
